### ISSUE TITLE
itysrv-python/python/中的readme中的几处纠正

### ISSUE THREAD

**Issue by lianghuiyuan** [IntoYun/intoyun-enterprise-demo-python#6]
1. 依赖库
- pip install pycrypto
- pip install kafka-python
- pip install futures
- pip install tornado
- pip install websocket-client
刚刚第一次在windows下使用，还提示`ImportError: No module named requests`和`ImportError: No module named websockets`
所以，依赖库还需要补全：
- pip install requests
- pip install websockets

2.表达不清晰

> 默认企业服务器使用IP "192.168.0.46", 请将如果有需要，请修改相应的配置文件(configs.system)的服务器IP;
- 这里需要将IP配置为安装服务的本机IP
- 配置文件(configs.system)是‘itysrv-python/python/configs/’目录下的‘system.py’文件

**Comment by zhongjin616** [comment]
Thanks. :)

README.md updated!
